J adan changes
jose-adan-synpulse/TM-Mini-Project pull request #1
Opened 2022-12-05 04:00 UTC by jose-adan-synpulse

Jose Adan change merge to main

2022-12-06 07:21 UTC, johnangelo-synpulse reviewed
Hi @jose-adan-synpulse ,
Please remove the unused commented codes in your files.

in your contracts take note of the looping, imagine having hundreds of thousands of data. If your looping can be optimized, please do.

2022-12-06 07:21 UTC, johnangelo-synpulse commented on savings-account-v2/savings-account-v2/casa/contracts/casa.py
> +    # raise InvalidContractParameter("monthly mean balance: %s" % _monthly_mean_balance(vault, denomination, effective_date))
Please remove unused code

2022-12-06 07:21 UTC, johnangelo-synpulse commented on savings-account-v2/savings-account-v2/casa/contracts/casa.py
> +    # raise InvalidContractParameter(f'printing: {effective_balance}')
please remove commented codes

2022-12-12 10:11 UTC, rjcalingaSP requested changes
Overall code is good, please address minor review points and run the tests again

2022-12-12 10:11 UTC, rjcalingaSP commented on savings-account-v2/savings-account-v2/casa/contracts/casa.py
> +def post_posting_code(postings, effective_date):
You can remove the `post_posting_code ` hook since it is not needed

2022-12-12 10:11 UTC, rjcalingaSP commented on savings-account-v2/savings-account-v2/casa/contracts/casa.py
> +    None
You may remove this `close_code` hook as well since there's no logic implemented

2022-12-13 03:29 UTC, jose-adan-synpulse commented
Committed the change for the review. Kindly advise if I can proceed with merging to main @rjcalingaSP @johnangelo-synpulse

2022-12-14 01:34 UTC, johnangelo-synpulse commented
Hi @jose-adan-synpulse ,
Good morning.

I am all good on my end, if it's okay with Sir @rjcalingaSP .
I think you can click merge it.

2022-12-14 04:02 UTC, rjcalingaSP approved these changes
lgtm. Approved :)

2022-12-14 04:03 UTC, merged

2022-12-14 05:28 UTC, johnangelo-synpulse commented
Congrats @jose-adan-synpulse
Hi Sir @rjcalingaSP ,  just an FYI on Jose's task, he will be doing now the ppt presentation, he told me that he is already done with the sim test in the postman so I gave him now the template for the ppt scenario.